### ISSUE TITLE
separate port for api and dashboard?

### ISSUE THREAD

**Issue by MajliTech** [k3nd0x/piglet#3]
Hello,
Why are those separate ports? You can connect it only for port 80 and api is reachable on /api. This saves unnecessary setup, and will free some ports.

**Comment by k3nd0x** [comment]
Hello, 
If you are not using the api external for programming stuff you don’t have to export the api port to the host. Just try it without the 8080:8080 in the docker compose file.

**Comment by MajliTech** [comment]
Ok. Thanks!
